CREATE TABLE `fitness_exercise` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`slug` text NOT NULL,
	`name` text NOT NULL,
	`type` text DEFAULT 'timed' NOT NULL,
	`image_url` text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `fitness_exercise_slug_unique` ON `fitness_exercise` (`slug`);--> statement-breakpoint
CREATE TABLE `fitness_exercise_preference` (
	`user_id` text NOT NULL,
	`exercise_id` integer NOT NULL,
	`speed_percent` integer DEFAULT 100 NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	PRIMARY KEY(`user_id`, `exercise_id`),
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`exercise_id`) REFERENCES `fitness_exercise`(`id`) ON UPDATE no action ON DELETE cascade,
	CONSTRAINT "fitnessExercisePreference_speed_check" CHECK("fitness_exercise_preference"."speed_percent" >= 25 AND "fitness_exercise_preference"."speed_percent" <= 200)
);
--> statement-breakpoint
CREATE INDEX `fitnessExercisePreference_exerciseId_idx` ON `fitness_exercise_preference` (`exercise_id`);--> statement-breakpoint
CREATE TABLE `fitness_program` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`slug` text NOT NULL,
	`name` text NOT NULL,
	`description` text NOT NULL,
	`duration_days` integer NOT NULL,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `fitness_program_slug_unique` ON `fitness_program` (`slug`);--> statement-breakpoint
CREATE TABLE `fitness_workout` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`program_id` integer NOT NULL,
	`day` integer NOT NULL,
	`title` text NOT NULL,
	`description` text NOT NULL,
	`image_url` text NOT NULL,
	`sets` integer NOT NULL,
	`rest_between_exercises` integer NOT NULL,
	`rest_between_sets` integer NOT NULL,
	FOREIGN KEY (`program_id`) REFERENCES `fitness_program`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `fitnessWorkout_programId_day_idx` ON `fitness_workout` (`program_id`,`day`);--> statement-breakpoint
CREATE INDEX `fitnessWorkout_programId_idx` ON `fitness_workout` (`program_id`);--> statement-breakpoint
CREATE TABLE `fitness_workout_exercise` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`workout_id` integer NOT NULL,
	`exercise_id` integer NOT NULL,
	`position` integer NOT NULL,
	`amount` integer NOT NULL,
	FOREIGN KEY (`workout_id`) REFERENCES `fitness_workout`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`exercise_id`) REFERENCES `fitness_exercise`(`id`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "fitnessWorkoutExercise_amount_check" CHECK("fitness_workout_exercise"."amount" > 0)
);
--> statement-breakpoint
CREATE UNIQUE INDEX `fitnessWorkoutExercise_workoutId_position_idx` ON `fitness_workout_exercise` (`workout_id`,`position`);--> statement-breakpoint
CREATE INDEX `fitnessWorkoutExercise_workoutId_idx` ON `fitness_workout_exercise` (`workout_id`);--> statement-breakpoint
CREATE INDEX `fitnessWorkoutExercise_exerciseId_idx` ON `fitness_workout_exercise` (`exercise_id`);--> statement-breakpoint
CREATE TABLE `fitness_workout_progress` (
	`user_id` text NOT NULL,
	`workout_id` integer NOT NULL,
	`completed_date` text NOT NULL,
	`completed_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	PRIMARY KEY(`user_id`, `completed_date`),
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`workout_id`) REFERENCES `fitness_workout`(`id`) ON UPDATE no action ON DELETE cascade,
	CONSTRAINT "fitnessWorkoutProgress_date_check" CHECK("fitness_workout_progress"."completed_date" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]')
);
--> statement-breakpoint
CREATE INDEX `fitnessWorkoutProgress_workoutId_idx` ON `fitness_workout_progress` (`workout_id`);
--> statement-breakpoint
INSERT INTO `fitness_program` (`id`,`slug`,`name`,`description`,`duration_days`) VALUES (1,'total-body-30','Total Body 30','A balanced 30-day program combining strength, core, cardio, mobility, and yoga.',30);
--> statement-breakpoint
INSERT INTO `fitness_exercise` (`id`,`slug`,`name`,`image_url`) VALUES
	(1,'back-extensions','Back Extensions','/fitness/activities/back-extensions.webp'),
	(2,'back-triceps-stretch-left','Back Triceps Stretch Left','/fitness/activities/back-triceps-stretch-left.webp'),
	(3,'back-triceps-stretch-right','Back Triceps Stretch Right','/fitness/activities/back-triceps-stretch-right.webp'),
	(4,'bird-dog-left','Bird Dog Left','/fitness/activities/bird-dog-left.webp'),
	(5,'bird-dog-right','Bird Dog Right','/fitness/activities/bird-dog-right.webp'),
	(6,'bridges','Bridges','/fitness/activities/bridges.webp'),
	(7,'butt-kicks','Butt Kicks','/fitness/activities/butt-kicks.webp'),
	(8,'butterfly-pose','Butterfly Pose','/fitness/activities/butterfly-pose.webp'),
	(9,'calf-raises','Calf Raises','/fitness/activities/calf-raises.webp'),
	(10,'chair-pose','Chair Pose','/fitness/activities/chair-pose.webp'),
	(11,'cossack-squats','Cossack Squats','/fitness/activities/cossack-squats.webp'),
	(12,'crunch-kicks','Crunch Kicks','/fitness/activities/crunch-kicks.webp'),
	(13,'dead-bug','Dead Bug','/fitness/activities/dead-bug.webp'),
	(14,'downward-dog-reach-back-left','Downward Dog Reach-Back Left','/fitness/activities/downward-dog-reach-back-left.webp'),
	(15,'downward-dog-reach-back-right','Downward Dog Reach-Back Right','/fitness/activities/downward-dog-reach-back-right.webp'),
	(16,'downward-facing-dog','Downward-Facing Dog','/fitness/activities/downward-facing-dog.webp'),
	(17,'extended-mountain-reach','Extended Mountain Reach','/fitness/activities/extended-mountain-reach.webp'),
	(18,'flutter-kicks','Flutter Kicks','/fitness/activities/flutter-kicks.webp'),
	(19,'forward-lunges','Forward Lunges','/fitness/activities/forward-lunges.webp'),
	(20,'get-ups','Get-Ups','/fitness/activities/get-ups.webp'),
	(21,'heel-taps','Heel Taps','/fitness/activities/heel-taps.webp'),
	(22,'high-crunches','High Crunches','/fitness/activities/high-crunches.webp'),
	(23,'high-knees','High Knees','/fitness/activities/high-knees.webp'),
	(24,'high-plank-hold','High Plank Hold','/fitness/activities/high-plank-hold.webp'),
	(25,'high-plank-hold-right','High Plank Hold Right','/fitness/activities/high-plank-hold-right.webp'),
	(26,'hollow-hold','Hollow Hold','/fitness/activities/hollow-hold.webp'),
	(27,'hops-on-the-spot','Hops on the Spot','/fitness/activities/hops-on-the-spot.webp'),
	(28,'jumping-jacks','Jumping Jacks','/fitness/activities/jumping-jacks.webp'),
	(29,'knee-in-twist','Knee-in Twist','/fitness/activities/knee-in-twist.webp'),
	(30,'knee-to-elbow','Knee-to-Elbow','/fitness/activities/knee-to-elbow.webp'),
	(31,'knees-hover-plank','Knees-Hover Plank','/fitness/activities/knees-hover-plank.webp'),
	(32,'left-leg-behind-swing','Left Leg Behind Swing','/fitness/activities/left-leg-behind-swing.webp'),
	(33,'left-leg-forward-raise-hold','Left Leg Forward Raise Hold','/fitness/activities/left-leg-forward-raise-hold.webp'),
	(34,'left-leg-forward-swing','Left Leg Forward Swing','/fitness/activities/left-leg-forward-swing.webp'),
	(35,'left-leg-side-raise-hold','Left Leg Side Raise Hold','/fitness/activities/left-leg-side-raise-hold.webp'),
	(36,'left-leg-side-swing','Left Leg Side Swing','/fitness/activities/left-leg-side-swing.webp'),
	(37,'leg-circles','Leg Circles','/fitness/activities/leg-circles.webp'),
	(38,'leg-raises','Leg Raises','/fitness/activities/leg-raises.webp'),
	(39,'lunge-step-ups','Lunge Step-Ups','/fitness/activities/lunge-step-ups.webp'),
	(40,'march-steps','March Steps','/fitness/activities/march-steps.webp'),
	(41,'overhead-triceps-stretch-left','Overhead Triceps Stretch Left','/fitness/activities/overhead-triceps-stretch-left.webp'),
	(42,'overhead-triceps-stretch-right','Overhead Triceps Stretch Right','/fitness/activities/overhead-triceps-stretch-right.webp'),
	(43,'pigeon-pose-left','Pigeon Pose Left','/fitness/activities/pigeon-pose-left.webp'),
	(44,'pigeon-pose-right','Pigeon Pose Right','/fitness/activities/pigeon-pose-right.webp'),
	(45,'plank-arm-raises','Plank Arm Raises','/fitness/activities/plank-arm-raises.webp'),
	(46,'plank-leg-raises','Plank Leg Raises','/fitness/activities/plank-leg-raises.webp'),
	(47,'plank-rotations','Plank Rotations','/fitness/activities/plank-rotations.webp'),
	(48,'prone-reverse-fly','Prone Reverse Fly','/fitness/activities/prone-reverse-fly.webp'),
	(49,'quadruped-donkey-kicks-left','Quadruped Donkey Kicks Left','/fitness/activities/quadruped-donkey-kicks-left.webp'),
	(50,'quadruped-donkey-kicks-right','Quadruped Donkey Kicks Right','/fitness/activities/quadruped-donkey-kicks-right.webp'),
	(51,'quadruped-straight-leg-raise-hold-left','Quadruped Straight-Leg Raise Hold Left','/fitness/activities/quadruped-straight-leg-raise-hold-left.webp'),
	(52,'quadruped-straight-leg-raise-hold-right','Quadruped Straight-Leg Raise Hold Right','/fitness/activities/quadruped-straight-leg-raise-hold-right.webp'),
	(53,'quadruped-straight-leg-raises-left','Quadruped Straight-Leg Raises Left','/fitness/activities/quadruped-straight-leg-raises-left.webp'),
	(54,'quadruped-straight-leg-raises-right','Quadruped Straight-Leg Raises Right','/fitness/activities/quadruped-straight-leg-raises-right.webp'),
	(55,'raised-legs-circles','Raised Legs Circles','/fitness/activities/raised-legs-circles.webp'),
	(56,'reclined-spinal-twist-left','Reclined Spinal Twist Left','/fitness/activities/reclined-spinal-twist-left.webp'),
	(57,'reclined-spinal-twist-right','Reclined Spinal Twist Right','/fitness/activities/reclined-spinal-twist-right.webp'),
	(58,'reverse-angels','Reverse Angels','/fitness/activities/reverse-angels.webp'),
	(59,'reverse-crunches','Reverse Crunches','/fitness/activities/reverse-crunches.webp'),
	(60,'reverse-deep-lunges','Reverse Deep Lunges','/fitness/activities/reverse-deep-lunges.webp'),
	(61,'reverse-lunges','Reverse Lunges','/fitness/activities/reverse-lunges.webp'),
	(62,'right-leg-behind-swing','Right Leg Behind Swing','/fitness/activities/right-leg-behind-swing.webp'),
	(63,'right-leg-forward-raise-hold','Right Leg Forward Raise Hold','/fitness/activities/right-leg-forward-raise-hold.webp'),
	(64,'right-leg-forward-swing','Right Leg Forward Swing','/fitness/activities/right-leg-forward-swing.webp'),
	(65,'right-leg-side-raise-hold','Right Leg Side Raise Hold','/fitness/activities/right-leg-side-raise-hold.webp'),
	(66,'right-leg-side-swing','Right Leg Side Swing','/fitness/activities/right-leg-side-swing.webp'),
	(67,'scissors','Scissors','/fitness/activities/scissors.webp'),
	(68,'seal-jacks','Seal Jacks','/fitness/activities/seal-jacks.webp'),
	(69,'seated-forward-fold-left','Seated Forward Fold Left','/fitness/activities/seated-forward-fold-left.webp'),
	(70,'seated-forward-fold-right','Seated Forward Fold Right','/fitness/activities/seated-forward-fold-right.webp'),
	(71,'seated-overhead-reach','Seated Overhead Reach','/fitness/activities/seated-overhead-reach.webp'),
	(72,'seated-straight-leg-hold-left','Seated Straight-Leg Hold Left','/fitness/activities/seated-straight-leg-hold-left.webp'),
	(73,'seated-straight-leg-hold-right','Seated Straight-Leg Hold Right','/fitness/activities/seated-straight-leg-hold-right.webp'),
	(74,'seated-straight-leg-swing-left','Seated Straight-Leg Swing Left','/fitness/activities/seated-straight-leg-swing-left.webp'),
	(75,'seated-straight-leg-swing-right','Seated Straight-Leg Swing Right','/fitness/activities/seated-straight-leg-swing-right.webp'),
	(76,'shoulder-taps','Shoulder Taps','/fitness/activities/shoulder-taps.webp'),
	(77,'side-bridges','Side Bridges','/fitness/activities/side-bridges.webp'),
	(78,'side-lying-straight-leg-hold-left','Side-Lying Straight-Leg Hold Left','/fitness/activities/side-lying-straight-leg-hold-left.webp'),
	(79,'side-lying-straight-leg-hold-right','Side-Lying Straight-Leg Hold Right','/fitness/activities/side-lying-straight-leg-hold-right.webp'),
	(80,'side-lying-straight-leg-raise-left','Side-Lying Straight-Leg Raise Left','/fitness/activities/side-lying-straight-leg-raise-left.webp'),
	(81,'side-lying-straight-leg-raise-right','Side-Lying Straight-Leg Raise Right','/fitness/activities/side-lying-straight-leg-raise-right.webp'),
	(82,'side-plank-left','Side Plank Left','/fitness/activities/side-plank-left.webp'),
	(83,'side-plank-right','Side Plank Right','/fitness/activities/side-plank-right.webp'),
	(84,'side-to-side-hops','Side-to-Side Hops','/fitness/activities/side-to-side-hops.webp'),
	(85,'side-to-side-lunges','Side-to-Side Lunges','/fitness/activities/side-to-side-lunges.webp'),
	(86,'single-leg-knee-lift-balance-left','Single-Leg Knee-Lift Balance Left','/fitness/activities/single-leg-knee-lift-balance-left.webp'),
	(87,'single-leg-knee-lift-balance-right','Single-Leg Knee-Lift Balance Right','/fitness/activities/single-leg-knee-lift-balance-right.webp'),
	(88,'sit-ups','Sit Ups','/fitness/activities/sit-ups.webp'),
	(89,'sitting-twists','Sitting Twists','/fitness/activities/sitting-twists.webp'),
	(90,'slow-climber-taps','Slow Climber Taps','/fitness/activities/slow-climber-taps.webp'),
	(91,'split-jacks','Split Jacks','/fitness/activities/split-jacks.webp'),
	(92,'split-lunges','Split Lunges','/fitness/activities/split-lunges.webp'),
	(93,'squats','Squats','/fitness/activities/squats.webp'),
	(94,'standing-straddle-stretch','Standing Straddle Stretch','/fitness/activities/standing-straddle-stretch.webp'),
	(95,'straight-leg-bounds','Straight Leg Bounds','/fitness/activities/straight-leg-bounds.webp'),
	(96,'tabletop-bridge-reach-left','Tabletop Bridge Reach Left','/fitness/activities/tabletop-bridge-reach-left.webp'),
	(97,'tabletop-bridge-reach-right','Tabletop Bridge Reach Right','/fitness/activities/tabletop-bridge-reach-right.webp'),
	(98,'thigh-taps','Thigh Taps','/fitness/activities/thigh-taps.webp'),
	(99,'three-legged-downward-dog-left','Three-Legged Downward Dog Left','/fitness/activities/three-legged-downward-dog-left.webp'),
	(100,'three-legged-downward-dog-right','Three-Legged Downward Dog Right','/fitness/activities/three-legged-downward-dog-right.webp'),
	(101,'toe-tap-hops','Toe Tap Hops','/fitness/activities/toe-tap-hops.webp'),
	(102,'up-down-planks','Up & Down Planks','/fitness/activities/up-&-down-planks.webp'),
	(103,'upward-facing-dog','Upward-Facing Dog','/fitness/activities/upward-facing-dog.webp'),
	(104,'w-extensions','W-Extensions','/fitness/activities/w-extensions.webp'),
	(105,'warrior-3-left','Warrior 3 Left','/fitness/activities/warrior-3-left.webp'),
	(106,'warrior-3-right','Warrior 3 Right','/fitness/activities/warrior-3-right.webp'),
	(107,'windshield-wipers','Windshield Wipers','/fitness/activities/windshield-wipers.webp');
--> statement-breakpoint
INSERT INTO `fitness_workout` (`id`,`program_id`,`day`,`title`,`description`,`image_url`,`sets`,`rest_between_exercises`,`rest_between_sets`) VALUES
	(1,1,1,'Total Body - Day 1: Build','Five-set total body routine inspired by Darebee''s Total Body Day 1: reverse lunges, split lunges, side-to-side lunges, shoulder taps and plank leg raises. Perform 5 sets in total with 60 seconds rest between exercises and 30 seconds rest between sets.','/fitness/workouts/day01.jpg',5,30,60),
	(2,1,2,'Total Body - Day 2: Abs & Core','Abs & Core workout. Level I: 3 sets, Level II: 5 sets, Level III: 7 sets. Rest up to 2 minutes between sets.','/fitness/workouts/day02.jpg',3,30,120),
	(3,1,3,'Total Body - Day 3: Cardio Burn','Cardio circuit alternating jumping jacks with toe tap hops, hops on the spot, and side-to-side hops.','/fitness/workouts/day03.jpg',3,30,120),
	(4,1,4,'Total Body - Day 4: Tendons','Repeat or hold each exercise for 30 seconds, then move on to the next, Repeat the sequence again on the other side.','/fitness/workouts/day04.jpg',1,30,30),
	(5,1,5,'Total Body - Day 5: Build','Build your upper body strength with this 5-set routine. Perform 5 sets in total with 60 seconds rest between exercises and 30 seconds rest between sets.','/fitness/workouts/day05.jpg',5,30,60),
	(6,1,6,'Total Body - Day 6: Cardio HIIT','Let''s get your heart rate up!','/fitness/workouts/day06.jpg',3,30,30),
	(7,1,7,'Total Body - Day 7: Yoga','Hold each pose for 30 seconds then move on to the next one. Repeat the sequence again on the other side.','/fitness/workouts/day07.jpg',1,10,30),
	(8,1,8,'Total Body - Day 8: Build','Five-set total body routine inspired by Darebee''s Total Body Day 8: split lunges, lunge step-ups, cossack squats, shoulder taps and up & down planks. Perform 5 sets in total with 60 seconds rest between exercises and 30 seconds rest between sets.','/fitness/workouts/day08.jpg',5,60,30),
	(9,1,9,'Total Body - Day 9: Abs & Core','Abs & core circuit inspired by Darebee''s Total Body Day 9: flutter kicks, leg circles, dead bug and back extensions. Perform 5 sets (Level III) with no rest between exercises and 2 minutes rest between sets.','/fitness/workouts/day09.jpg',5,0,120),
	(10,1,10,'Total Body - Day 10: Cardio Burn','Cardio burn circuit: jumping jacks, knee-to-elbow, jumping jacks, hops on the spot, seal jacks and side-to-side hops. Perform 7 sets (Level III) with 2 minutes rest between sets.','/fitness/workouts/day10.jpg',7,0,120),
	(11,1,11,'Total Body - Day 11: Tendons','Repeat or hold each exercise for 30 seconds, then move on to the next. Repeat the sequence again on the other side.','/fitness/workouts/day11.jpg',1,30,30),
	(12,1,12,'Total Body - Day 12: Build','Five-set total body routine: bridges, get-ups, reverse angels, prone reverse fly and W-extensions. Perform 5 sets in total with 60 seconds rest between exercises and 30 seconds rest between sets.','/fitness/workouts/day12.jpg',5,60,30),
	(13,1,13,'Total Body - Day 13: Cardio HIIT','30-second intervals: split jacks, high knees, split jacks, butt kicks, split jacks and butt kicks. Perform 7 sets (Level III) with 2 minutes rest between sets.','/fitness/workouts/day13.jpg',7,0,120),
	(14,1,14,'Total Body - Day 14: Yoga','Hold each pose for 30 seconds then move on to the next one. Repeat the sequence again on the other side.','/fitness/workouts/day14.jpg',1,10,30),
	(15,1,15,'Total Body - Day 15: Build','Five-set total body routine: reverse lunges, side-to-side lunges, forward lunges, shoulder taps and plank rotations. Perform 5 sets in total with 60 seconds rest between exercises and 30 seconds rest between sets.','/fitness/workouts/day15.jpg',5,60,30),
	(16,1,16,'Total Body - Day 16: Abs & Core','Abs & core circuit: high crunches, sitting twists, crunch kicks and leg raises. Perform 5 sets (Level III) with 2 minutes rest between sets.','/fitness/workouts/day16.jpg',5,10,120),
	(17,1,17,'Total Body - Day 17: Cardio Burn','Cardio burn circuit: toe tap hops, jumping jacks, toe tap hops, jumping jacks, hops on the spot and jumping jacks. Perform 7 sets (Level III) with 2 minutes rest between sets.','/fitness/workouts/day17.jpg',7,0,120),
	(18,1,18,'Total Body - Day 18: Tendons','Repeat or hold each exercise for 30 seconds then move on to the next. Repeat the sequence again on the other side.','/fitness/workouts/day18.jpg',1,30,30),
	(19,1,19,'Total Body - Day 19: Build','Five-set total body routine: squats, calf raises, shoulder taps, plank arm raises and thigh taps. Perform 5 sets in total with 60 seconds rest between exercises and 30 seconds rest between sets.','/fitness/workouts/day19.jpg',5,60,30),
	(20,1,20,'Total Body - Day 20: Cardio HIIT','30-second intervals: high knees, straight leg bounds, high knees, butt kicks, high knees and butt kicks. Perform 7 sets (Level III) with 2 minutes rest between sets.','/fitness/workouts/day20.jpg',7,0,120),
	(21,1,21,'Total Body - Day 21: Yoga','Hold each pose for 30 seconds then move on to the next one. Repeat the sequence again on the other side.','/fitness/workouts/day21.jpg',1,10,30),
	(22,1,22,'Total Body - Day 22: Build','Five-set total body routine: cossack squats, reverse deep lunges, shoulder taps and slow climber taps. Perform 5 sets in total with 60 seconds rest between exercises and 30 seconds rest between sets.','/fitness/workouts/day22.jpg',5,60,30),
	(23,1,23,'Total Body - Day 23: Abs & Core','Abs & core circuit: knee-to-elbow, heel taps, scissors and windshield wipers. Perform 5 sets (Level III) with 2 minutes rest between sets.','/fitness/workouts/day23.jpg',5,0,120),
	(24,1,24,'Total Body - Day 24: Cardio Burn','Cardio burn circuit: jumping jacks, knee-to-elbow, jumping jacks, seal jacks, jumping jacks and seal jacks. Perform 7 sets (Level III) with 2 minutes rest between sets.','/fitness/workouts/day24.jpg',7,0,120),
	(25,1,25,'Total Body - Day 25: Tendons','Repeat or hold each exercise for 30 seconds then move on to the next one. Repeat the sequence again on the other side.','/fitness/workouts/day25.jpg',1,30,30),
	(26,1,26,'Total Body - Day 26: Build','Five-set total body routine: bridges, side bridges, reverse angels, prone reverse fly and W-extensions. Perform 5 sets in total with 60 seconds rest between exercises and 30 seconds rest between sets.','/fitness/workouts/day26.jpg',5,60,30),
	(27,1,27,'Total Body - Day 27: Cardio HIIT','30-second intervals: high knees, butt kicks, high knees, split jacks, straight leg bounds and split jacks. Perform 7 sets (Level III) with 2 minutes rest between sets.','/fitness/workouts/day27.jpg',7,0,120),
	(28,1,28,'Total Body - Day 28: Yoga','Hold each pose for 30 seconds then move on to the next one. Repeat the sequence again on the other side.','/fitness/workouts/day28.jpg',1,10,30),
	(29,1,29,'Total Body - Day 29: Build','Five-set total body routine: split lunges, lunge step-ups, side-to-side lunges, shoulder taps, plank rotations and plank leg raises. Perform 5 sets in total with 60 seconds rest between exercises and 30 seconds rest between sets.','/fitness/workouts/day29.jpg',5,60,30),
	(30,1,30,'Total Body - Day 30: Abs & Core','Abs & core circuit: leg raises, flutter kicks, raised legs circles and a hollow hold. Perform 5 sets (Level III) with 2 minutes rest between sets.','/fitness/workouts/day30.jpg',5,0,120);
--> statement-breakpoint
INSERT INTO `fitness_workout_exercise` (`id`,`workout_id`,`exercise_id`,`position`,`amount`) VALUES
	(1,1,61,1,14),
	(2,1,92,2,14),
	(3,1,85,3,14),
	(4,1,76,4,24),
	(5,1,46,5,24),
	(6,2,29,1,10),
	(7,2,88,2,10),
	(8,2,59,3,10),
	(9,2,1,4,10),
	(10,3,28,1,10),
	(11,3,101,2,10),
	(12,3,28,3,10),
	(13,3,27,4,10),
	(14,3,28,5,10),
	(15,3,84,6,10),
	(16,4,36,1,30),
	(17,4,66,2,30),
	(18,4,94,3,30),
	(19,4,32,4,30),
	(20,4,62,5,30),
	(21,4,94,6,30),
	(22,4,34,7,30),
	(23,4,64,8,30),
	(24,4,94,9,30),
	(25,5,93,1,14),
	(26,5,9,2,14),
	(27,5,47,3,14),
	(28,5,45,4,14),
	(29,5,98,5,14),
	(30,6,23,1,30),
	(31,6,7,2,30),
	(32,6,23,3,30),
	(33,6,40,4,30),
	(34,6,23,5,30),
	(35,6,91,6,30),
	(36,7,16,1,30),
	(37,7,15,2,30),
	(38,7,14,3,30),
	(39,7,83,4,30),
	(40,7,82,5,30),
	(41,7,100,6,30),
	(42,7,99,7,30),
	(43,7,25,8,30),
	(44,7,5,9,30),
	(45,7,4,10,30),
	(46,8,92,1,14),
	(47,8,39,2,14),
	(48,8,11,3,14),
	(49,8,76,4,24),
	(50,8,102,5,8),
	(51,9,18,1,10),
	(52,9,37,2,10),
	(53,9,13,3,10),
	(54,9,1,4,10),
	(55,10,28,1,10),
	(56,10,30,2,10),
	(57,10,28,3,10),
	(58,10,27,4,10),
	(59,10,68,5,10),
	(60,10,84,6,10),
	(61,11,81,1,30),
	(62,11,79,2,30),
	(63,11,81,3,30),
	(64,11,75,4,30),
	(65,11,73,5,30),
	(66,11,75,6,30),
	(67,11,80,7,30),
	(68,11,78,8,30),
	(69,11,80,9,30),
	(70,11,74,10,30),
	(71,11,72,11,30),
	(72,11,74,12,30),
	(73,12,6,1,24),
	(74,12,20,2,24),
	(75,12,58,3,14),
	(76,12,48,4,14),
	(77,12,104,5,14),
	(78,13,91,1,30),
	(79,13,23,2,30),
	(80,13,91,3,30),
	(81,13,7,4,30),
	(82,13,91,5,30),
	(83,13,7,6,30),
	(84,14,17,1,30),
	(85,14,10,2,30),
	(86,14,17,3,30),
	(87,14,87,4,30),
	(88,14,106,5,30),
	(89,14,87,6,30),
	(90,14,86,7,30),
	(91,14,105,8,30),
	(92,14,86,9,30),
	(93,15,61,1,16),
	(94,15,85,2,16),
	(95,15,19,3,16),
	(96,15,76,4,24),
	(97,15,47,5,24),
	(98,16,22,1,12),
	(99,16,89,2,12),
	(100,16,12,3,12),
	(101,16,38,4,12),
	(102,17,101,1,12),
	(103,17,28,2,12),
	(104,17,101,3,12),
	(105,17,28,4,12),
	(106,17,27,5,12),
	(107,17,28,6,12),
	(108,18,32,1,30),
	(109,18,34,2,30),
	(110,18,33,3,30),
	(111,18,36,4,30),
	(112,18,35,5,30),
	(113,18,94,6,30),
	(114,18,62,7,30),
	(115,18,64,8,30),
	(116,18,63,9,30),
	(117,18,66,10,30),
	(118,18,65,11,30),
	(119,18,94,12,30),
	(120,19,93,1,16),
	(121,19,9,2,16),
	(122,19,76,3,28),
	(123,19,45,4,16),
	(124,19,98,5,16),
	(125,20,23,1,30),
	(126,20,95,2,30),
	(127,20,23,3,30),
	(128,20,7,4,30),
	(129,20,23,5,30),
	(130,20,7,6,30),
	(131,21,71,1,30),
	(132,21,42,2,30),
	(133,21,41,3,30),
	(134,21,2,4,30),
	(135,21,3,5,30),
	(136,21,8,6,30),
	(137,21,70,7,30),
	(138,21,69,8,30),
	(139,21,44,9,30),
	(140,21,43,10,30),
	(141,22,11,1,28),
	(142,22,60,2,28),
	(143,22,76,3,28),
	(144,22,90,4,28),
	(145,23,30,1,12),
	(146,23,21,2,12),
	(147,23,67,3,12),
	(148,23,107,4,12),
	(149,24,28,1,14),
	(150,24,30,2,14),
	(151,24,28,3,14),
	(152,24,68,4,14),
	(153,24,28,5,14),
	(154,24,68,6,14),
	(155,25,54,1,30),
	(156,25,53,2,30),
	(157,25,52,3,30),
	(158,25,51,4,30),
	(159,25,54,5,30),
	(160,25,53,6,30),
	(161,25,50,7,30),
	(162,25,49,8,30),
	(163,26,6,1,28),
	(164,26,77,2,28),
	(165,26,58,3,16),
	(166,26,48,4,16),
	(167,26,104,5,16),
	(168,27,23,1,30),
	(169,27,7,2,30),
	(170,27,23,3,30),
	(171,27,91,4,30),
	(172,27,95,5,30),
	(173,27,91,6,30),
	(174,28,24,1,30),
	(175,28,31,2,30),
	(176,28,16,3,30),
	(177,28,103,4,30),
	(178,28,57,5,30),
	(179,28,97,6,30),
	(180,28,56,7,30),
	(181,28,96,8,30),
	(182,29,92,1,18),
	(183,29,39,2,18),
	(184,29,85,3,18),
	(185,29,76,4,26),
	(186,29,47,5,26),
	(187,29,46,6,26),
	(188,30,38,1,14),
	(189,30,18,2,14),
	(190,30,55,3,14),
	(191,30,26,4,10);
--> statement-breakpoint
UPDATE `fitness_exercise` SET `type` = 'reps' WHERE `id` IN (1,6,9,11,12,13,18,19,20,21,22,27,28,29,30,37,38,39,45,46,47,48,55,58,59,60,61,67,68,76,77,84,85,88,89,90,92,93,98,101,102,104,107);
--> statement-breakpoint
CREATE TRIGGER `fitness_exercise_preference_reps_insert`
BEFORE INSERT ON `fitness_exercise_preference`
FOR EACH ROW
WHEN COALESCE((SELECT `type` FROM `fitness_exercise` WHERE `id` = NEW.`exercise_id`), 'timed') <> 'reps'
BEGIN
	SELECT RAISE(ABORT, 'speed preferences are only valid for rep-based exercises');
END;
--> statement-breakpoint
CREATE TRIGGER `fitness_exercise_preference_reps_update`
BEFORE UPDATE ON `fitness_exercise_preference`
FOR EACH ROW
WHEN COALESCE((SELECT `type` FROM `fitness_exercise` WHERE `id` = NEW.`exercise_id`), 'timed') <> 'reps'
BEGIN
	SELECT RAISE(ABORT, 'speed preferences are only valid for rep-based exercises');
END;
